# permissions for end users to view cassandraclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cassandracluster-viewer-role
rules:
- apiGroups:
  - cassandra.apache.org
  resources:
  - cassandraclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cassandra.apache.org
  resources:
  - cassandraclusters/status
  verbs:
  - get
